### ISSUE TITLE
TypeError: ArrayField.empty_field: return type `None` is not a `allennlp.data.fields.field.Field`.

### ISSUE THREAD

**Issue by zhaozj89** [PKU-TANGENT/NeuralEDUSeg#10]
I ran the segmentation example `python run.py --segment --input_files ../data/rst/TRAINING/wsj_110*.out --result_dir ../data/results/`, but always got this error. And ideas? Thanks.

**Comment by JarenceSJ** [comment]
same issue,  how did you address it?

**Comment by zhaozj89** [comment]
https://github.com/NLPbox/rstweb-service I used this docker and ran the package successfully.
